const sql = require('mssql');
const dbConfig = require('../config/db.config');

// Get all announcements
async function getAllAnnouncements() {
  const pool = await sql.connect(dbConfig);
  const result = await pool.request()
    .query('SELECT * FROM AnnouncementTable ORDER BY CreatedDate DESC');
  return result.recordset;
}

// Get announcement by AnnouncementID
async function getAnnouncementById(AnnouncementID) {
  const pool = await sql.connect(dbConfig);
  const result = await pool.request()
    .input('AnnouncementID', sql.VarChar(30), AnnouncementID)
    .query('SELECT * FROM AnnouncementTable WHERE AnnouncementID = @AnnouncementID');
  return result.recordset[0];
}

// Add announcement
async function addAnnouncement(data) {
  const pool = await sql.connect(dbConfig);
  await pool.request()
    .input('AnnouncementID', sql.VarChar(30), data.AnnouncementID) // Must be generated by the caller (UUID or similar)
    .input('EmpID', sql.VarChar(30), data.EmpID)
    .input('Title', sql.VarChar(50), data.Title)
    .input('Description', sql.VarChar(1000), data.Description)
    .input('CreatedDate', sql.Date, data.CreatedDate || new Date())
    .query(`INSERT INTO AnnouncementTable
      (AnnouncementID, EmpID, Title, Description, CreatedDate)
      VALUES (@AnnouncementID, @EmpID, @Title, @Description, @CreatedDate)
    `);
}

// Update announcement by AnnouncementID
async function updateAnnouncement(data) {
  const pool = await sql.connect(dbConfig);
  await pool.request()
    .input('AnnouncementID', sql.VarChar(30), data.AnnouncementID)
    .input('Title', sql.VarChar(50), data.Title)
    .input('Description', sql.VarChar(1000), data.Description)
    .query(`UPDATE AnnouncementTable
      SET Title = @Title, Description = @Description
      WHERE AnnouncementID = @AnnouncementID
    `);
}

// Delete announcement by AnnouncementID
async function deleteAnnouncement(AnnouncementID) {
  const pool = await sql.connect(dbConfig);
  await pool.request()
    .input('AnnouncementID', sql.VarChar(30), AnnouncementID)
    .query('DELETE FROM AnnouncementTable WHERE AnnouncementID = @AnnouncementID');
}

module.exports = {
  getAllAnnouncements,
  getAnnouncementById,
  addAnnouncement,
  updateAnnouncement,
  deleteAnnouncement,
};
